#!/usr/bin/env python3
"""Compose agent context fragments into per-surface profiles, and verify them.

ADR-0018 decides that surface differences are resolved when content is
delivered, not by the agent at runtime. This is the program that resolves
them: fragments in `context/fragments/` are the source, `context/manifest.json`
says which compose into which output, and every output is committed.

Two modes, one code path:

    python3 tests/compose-context.py            # verify (CI); non-zero on drift
    python3 tests/compose-context.py --write    # regenerate after editing a fragment

Deliberately not a template engine. A template engine's headline feature is
conditional rendering, which is the construct ADR-0018 principle 1 exists to
remove: concatenation makes a surface conditional impossible to express rather
than merely discouraged. See #249 for the full reasoning.

Two kinds of output, one mechanism. `profiles` composes always-loaded policy
(`AGENTS.md` / `CLAUDE.md`). `skills` composes **skill bodies** — the same
fragment-and-concatenate idea applied one tier down (ADR-0018 principle 2), so
that a sandbox skill says "call the MCP tool" where the workstation one says
"read the `gh` section the gather produced", instead of one body carrying both
and asking the agent to pick (#265).

The two differ only in assembly, because their file shapes differ. A policy
artefact gets an injected H1 title and every fragment demoted under it; a skill
body already has its own frontmatter and H1, carried by its first fragment, so
skill fragments are concatenated verbatim. That first fragment is the `head`:
`head-skill`, carrying the frontmatter and the H1. A `head-command` sat beside
it while each skill also composed to a `home/commands/` twin, which needs a
one-line description instead of frontmatter; the twins were retired (#313) and
it went with them.

Checks, per ADR-0018 principle 7 — deterministic delivery converts loud
failures into quiet ones, so the build is what catches them:

1. every committed output matches what the fragments currently produce
2. no non-workstation profile includes a workstation-only fragment
3. every policy output has exactly one H1, so markdownlint MD025 holds
4. always-loaded line counts are reported against the budget
5. every file under `profiles/` is claimed by the manifest
6. every fragment under `context/skills/` is used by at least one output
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "context" / "manifest.json"

# Claude Code targets under 200 lines of always-loaded policy; imports count.
# Exceeding it is reported, not fatal: the number existing in the build is the
# point, and the fix is a content decision (ADR-0018 principle 2), not a
# mechanical one this script can make.
BUDGET_LINES = 200

HEADING = re.compile(r"^(#{1,5})(\s+\S)", re.M)
FENCE = re.compile(r"^(```|~~~)")


def demote(text):
    """Add one level to every heading outside fenced code blocks.

    Fragments are authored as standalone documents with their own H1 so they
    read on their own. A composed file may have only one H1 (MD025), so each
    fragment becomes an H2 section under the profile title.
    """
    out, in_fence = [], False
    for line in text.split("\n"):
        if FENCE.match(line):
            in_fence = not in_fence
        out.append(line if in_fence else HEADING.sub(r"#\1\2", line))
    return "\n".join(out)


def h1_count(text):
    """Level-1 headings, ignoring fenced code blocks.

    `demote()` has always skipped fences; check 3 below did not, and read the
    same text with a different set of rules. A shell example whose comment
    starts at column 0 --

        # git@github.com:owner/repo.git

    -- counted as a heading, so a perfectly well-formed fragment failed
    composition with "4 level-1 headings, expected 1" and no clue why. Sharing
    the fence state is the fix; two readers of one document must agree on what
    a heading is.
    """
    count, in_fence = 0, False
    for line in text.split("\n"):
        if FENCE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = HEADING.match(line)
        if match and match.group(1) == "#":
            count += 1
    return count


def banner(profile, output, fragments):
    return (
        f"<!-- GENERATED by tests/compose-context.py from context/manifest.json.\n"
        f"     Profile: {profile}\n"
        f"     Fragments: {', '.join(fragments)}\n"
        f"     Do not edit this file. Edit the fragments in context/fragments/\n"
        f"     and run: python3 tests/compose-context.py --write -->"
    )


def skill_banner(skill, fragment_dir, fragments):
    return (
        f"<!-- GENERATED by tests/compose-context.py from context/manifest.json.\n"
        f"     Skill: {skill}\n"
        f"     Fragments: {', '.join(fragments)}\n"
        f"     Do not edit this file. Edit the fragments in {fragment_dir}/{skill}/\n"
        f"     and run: python3 tests/compose-context.py --write -->"
    )


def compose_skill(manifest, skill, fragments):
    """Concatenate skill fragments verbatim, banner after the head fragment.

    No demotion and no injected title, unlike a policy artefact: a skill body
    owns its own heading structure, and its first fragment is the head that
    carries the frontmatter (or, for the command twin, the description line).

    The banner cannot go first. A `SKILL.md` must open with `---` for the
    frontmatter to parse — `cloud/bootstrap.sh` checks exactly that on every
    fetch — and a command's first line IS its description, so a banner there
    would become the text the model reads as the command's purpose.
    """
    frag_dir = ROOT / manifest["skill_fragment_dir"]
    if not fragments:
        raise SystemExit(f"{skill}: output has no fragments")

    parts = []
    for i, name in enumerate(fragments):
        path = frag_dir / skill / f"{name}.md"
        if not path.exists():
            raise SystemExit(f"{skill}: no such fragment: {path}")
        parts.append(path.read_text().strip("\n"))
        if i == 0:
            parts.append(skill_banner(skill, manifest["skill_fragment_dir"], fragments))
    return "\n\n".join(parts) + "\n"


def compose(manifest, profile, output, fragments):
    frag_dir = ROOT / manifest["fragment_dir"]
    parts = [banner(profile, output, fragments), ""]
    parts.append(f"# {manifest['profiles'][profile]['title']}")
    for name in fragments:
        path = frag_dir / f"{name}.md"
        if not path.exists():
            raise SystemExit(f"{profile}: no such fragment: {path}")
        parts.append("")
        parts.append(demote(path.read_text()).rstrip("\n"))
    return "\n".join(parts) + "\n"


VARIANT_SUFFIX = re.compile(r"-(?:workstation|sandbox)$")


def variant_ratio(manifest, skill):
    """Report how many of a skill's sections carry a per-surface variant.

    ADR-0018 principle 8: the default is one shared body, and a split has to
    earn itself. This is that bar expressed as a number in the build, the same
    way the line count expresses the always-loaded budget — a report, never a
    gate. A high ratio is a content decision, and a build that failed on one
    would be a build people learn to override.

    It is worth watching because a variant pair is the one thing here that no
    check can guard. A skill and its command twin must be byte-identical, so
    drift between them fails the build; two variants of a section are supposed
    to differ, so a fix landing on one and missing the other is silent until
    somebody reads that surface's artefact.
    """
    frag_dir = ROOT / manifest["skill_fragment_dir"] / skill
    sections, varying = set(), set()
    for path in frag_dir.glob("*.md"):
        stem = path.stem
        if stem.startswith("00-head-"):
            continue  # the head is per-output shape, not a surface variant
        base = VARIANT_SUFFIX.sub("", stem)
        sections.add(base)
        if base != stem:
            varying.add(base)
    if not sections:
        return ""
    pct = round(100 * len(varying) / len(sections))
    return f"{len(varying)}/{len(sections)} sections carry a surface variant ({pct}%)"


def emit(output, expected, write, failures, wrote):
    """Write or verify one composed artefact. Shared by both output kinds."""
    path = ROOT / output
    if write:
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text() != expected:
            path.write_text(expected)
            wrote.append(output)
    elif not path.exists():
        failures.append(f"{output}: missing — run with --write")
    elif path.read_text() != expected:
        failures.append(f"{output}: stale — fragments changed; run with --write")


def main():
    write = "--write" in sys.argv
    manifest = json.loads(MANIFEST.read_text())
    env_fragments = set(manifest["environment_fragments"])

    failures, wrote = [], []
    for profile, spec in manifest["profiles"].items():
        own_env = spec["environment"]
        for output, fragments in spec["outputs"].items():

            # Check 2. The failure this prevents is shipping "run chezmoi
            # apply" to a surface with no chezmoi — wrong policy stated with
            # full confidence, which is worse than no policy.
            foreign = [f for f in fragments if f in env_fragments and f != own_env]
            if foreign:
                failures.append(
                    f"{profile} -> {output}: includes environment fragment(s) "
                    f"{foreign} but its environment is '{own_env}'"
                )
                continue

            expected = compose(manifest, profile, output, fragments)
            path = ROOT / output

            # Check 3.
            h1 = h1_count(expected)
            if h1 != 1:
                failures.append(f"{profile} -> {output}: {h1} level-1 headings, expected 1")

            lines = len(expected.splitlines())
            flag = "  OVER BUDGET" if lines > BUDGET_LINES else ""
            print(f"  {output:52s} {lines:4d} lines{flag}")

            emit(output, expected, write, failures, wrote)

    # Skill bodies. Same source-of-truth rule, one tier down: no budget line,
    # because a skill body costs nothing until the skill is invoked (ADR-0018
    # principle 2), and no H1 check here — markdownlint enforces MD025 over
    # every output anyway. The check was skipped originally because the two
    # output shapes disagreed on purpose: a SKILL.md has exactly one H1, and
    # its home/commands/ twin had none. The twins are gone (#313); adding an
    # H1 check for skills is a small piece of tightening, not done here.
    used_fragments = set()
    if manifest.get("skills"):
        print()
        for skill, spec in manifest["skills"].items():
            for output, fragments in spec["outputs"].items():
                expected = compose_skill(manifest, skill, fragments)
                used_fragments.update(
                    ROOT / manifest["skill_fragment_dir"] / skill / f"{name}.md"
                    for name in fragments
                )
                print(f"  {output:52s} {len(expected.splitlines()):4d} lines")
                emit(output, expected, write, failures, wrote)
            print(f"  {'':52s} {variant_ratio(manifest, skill)}")

    # Check 5. Every file under profiles/ must be claimed by the manifest.
    #
    # Added after a real miss: a `git checkout context/manifest.json` during an
    # unrelated test silently reverted two profiles, and the outputs they had
    # already written stayed on disk and got committed. Nothing noticed —
    # checks 1-4 only look at what the manifest declares, so a profile that
    # vanishes from the manifest takes its own verification with it. An
    # orphaned generated file is worse than a missing one: it looks current,
    # and it is the surface nobody is watching that reads it.
    declared = {
        ROOT / output
        for group in (manifest["profiles"], manifest.get("skills", {}))
        for spec in group.values()
        for output in spec["outputs"]
    }
    profiles_dir = ROOT / "profiles"
    if profiles_dir.is_dir():
        for path in sorted(profiles_dir.rglob("*")):
            if path.is_file() and path not in declared:
                failures.append(
                    f"{path.relative_to(ROOT)}: not declared by any profile — "
                    f"delete it, or restore the manifest entry that produced it"
                )

    # Check 6. The mirror image, for skill fragments: every file under
    # context/skills/ must be used by at least one output.
    #
    # A policy fragment that stops being referenced still shows up as an
    # orphaned artefact under profiles/, which check 5 catches. A skill
    # fragment leaves nothing behind — dropping a name from a manifest list
    # just makes that section quietly stop shipping, on every surface, with a
    # green build. The composed outputs shrink, and nothing says why.
    skills_dir = ROOT / manifest["skill_fragment_dir"]
    if manifest.get("skills") and skills_dir.is_dir():
        for path in sorted(skills_dir.rglob("*.md")):
            if path not in used_fragments:
                failures.append(
                    f"{path.relative_to(ROOT)}: unused — no output lists it. "
                    f"Add it to a manifest fragment list, or delete it"
                )

    if failures:
        print("\ncomposition failed:", file=sys.stderr)
        for f in failures:
            print(f"  {f}", file=sys.stderr)
        return 1

    if write:
        print(f"\nwrote {len(wrote)} file(s)" + (": " + ", ".join(wrote) if wrote else " (all current)"))
    else:
        print(f"\nall composed outputs match their fragments "
              f"(budget {BUDGET_LINES} lines for always-loaded policy)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
