#!/usr/bin/env python3
"""Compose agent context fragments into per-surface profiles, and verify them.

ADR-0018 decides that surface differences are resolved when content is
delivered, not by the agent at runtime. This is the program that resolves
them: fragments in `context/fragments/` are the source, `context/manifest.json`
says which compose into which output, and every output is committed.

Two modes, one code path:

    python3 tests/compose-context.py            # verify (CI); non-zero on drift
    python3 tests/compose-context.py --write    # regenerate after editing a fragment

Deliberately not a template engine. A template engine's headline feature is
conditional rendering, which is the construct ADR-0018 principle 1 exists to
remove: concatenation makes a surface conditional impossible to express rather
than merely discouraged. See #249 for the full reasoning.

Checks, per ADR-0018 principle 7 — deterministic delivery converts loud
failures into quiet ones, so the build is what catches them:

1. every committed output matches what the fragments currently produce
2. no non-workstation profile includes a workstation-only fragment
3. every output has exactly one H1, so markdownlint MD025 holds
4. always-loaded line counts are reported against the budget
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "context" / "manifest.json"

# Claude Code targets under 200 lines of always-loaded policy; imports count.
# Exceeding it is reported, not fatal: the number existing in the build is the
# point, and the fix is a content decision (ADR-0018 principle 2), not a
# mechanical one this script can make.
BUDGET_LINES = 200

HEADING = re.compile(r"^(#{1,5})(\s+\S)", re.M)
FENCE = re.compile(r"^(```|~~~)")


def demote(text):
    """Add one level to every heading outside fenced code blocks.

    Fragments are authored as standalone documents with their own H1 so they
    read on their own. A composed file may have only one H1 (MD025), so each
    fragment becomes an H2 section under the profile title.
    """
    out, in_fence = [], False
    for line in text.split("\n"):
        if FENCE.match(line):
            in_fence = not in_fence
        out.append(line if in_fence else HEADING.sub(r"#\1\2", line))
    return "\n".join(out)


def banner(profile, output, fragments):
    return (
        f"<!-- GENERATED by tests/compose-context.py from context/manifest.json.\n"
        f"     Profile: {profile}\n"
        f"     Fragments: {', '.join(fragments)}\n"
        f"     Do not edit this file. Edit the fragments in context/fragments/\n"
        f"     and run: python3 tests/compose-context.py --write -->"
    )


def compose(manifest, profile, output, fragments):
    frag_dir = ROOT / manifest["fragment_dir"]
    parts = [banner(profile, output, fragments), ""]
    parts.append(f"# {manifest['profiles'][profile]['title']}")
    for name in fragments:
        path = frag_dir / f"{name}.md"
        if not path.exists():
            raise SystemExit(f"{profile}: no such fragment: {path}")
        parts.append("")
        parts.append(demote(path.read_text()).rstrip("\n"))
    return "\n".join(parts) + "\n"


def main():
    write = "--write" in sys.argv
    manifest = json.loads(MANIFEST.read_text())
    env_fragments = set(manifest["environment_fragments"])

    failures, wrote = [], []
    for profile, spec in manifest["profiles"].items():
        own_env = spec["environment"]
        for output, fragments in spec["outputs"].items():

            # Check 2. The failure this prevents is shipping "run chezmoi
            # apply" to a surface with no chezmoi — wrong policy stated with
            # full confidence, which is worse than no policy.
            foreign = [f for f in fragments if f in env_fragments and f != own_env]
            if foreign:
                failures.append(
                    f"{profile} -> {output}: includes environment fragment(s) "
                    f"{foreign} but its environment is '{own_env}'"
                )
                continue

            expected = compose(manifest, profile, output, fragments)
            path = ROOT / output

            # Check 3.
            h1 = len([m for m in HEADING.finditer(expected) if m.group(1) == "#"])
            if h1 != 1:
                failures.append(f"{profile} -> {output}: {h1} level-1 headings, expected 1")

            lines = len(expected.splitlines())
            flag = "  OVER BUDGET" if lines > BUDGET_LINES else ""
            print(f"  {output:52s} {lines:4d} lines{flag}")

            if write:
                path.parent.mkdir(parents=True, exist_ok=True)
                if not path.exists() or path.read_text() != expected:
                    path.write_text(expected)
                    wrote.append(output)
            elif not path.exists():
                failures.append(f"{output}: missing — run with --write")
            elif path.read_text() != expected:
                failures.append(f"{output}: stale — fragments changed; run with --write")

    if failures:
        print("\ncomposition failed:", file=sys.stderr)
        for f in failures:
            print(f"  {f}", file=sys.stderr)
        return 1

    if write:
        print(f"\nwrote {len(wrote)} file(s)" + (": " + ", ".join(wrote) if wrote else " (all current)"))
    else:
        print(f"\nall composed outputs match their fragments "
              f"(budget {BUDGET_LINES} lines for always-loaded policy)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
